DROP TABLE IF EXISTS supplier_order;

CREATE TABLE supplier_order (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_date DATE DEFAULT now
(),
    item INTEGER references item
(id) NOT NULL,
    amount NUMERIC,
    total_cost NUMERIC,
    shipping_status TEXT
);